# Generated by Django 2.2.6 on 2019-11-03 11:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='velocityuser',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='')),
                ('business_name', models.CharField(default='', max_length=100, verbose_name='Business Name')),
                ('business_email', models.EmailField(blank=True, default='', max_length=254, verbose_name='Business Email')),
                ('business_registration_number', models.CharField(default='', max_length=50, verbose_name='Regsitration Number')),
                ('shop_name', models.CharField(default='', max_length=50, verbose_name='Shop Name')),
                ('tax_id', models.CharField(default='', max_length=100, verbose_name='Tax Identification Number')),
                ('country', models.CharField(max_length=100, verbose_name='Country')),
                ('region', models.CharField(max_length=100, verbose_name='State/Region/Province')),
                ('city', models.CharField(max_length=100, verbose_name='City')),
                ('bank_name', models.CharField(max_length=100, verbose_name='Bank')),
                ('account_number', models.CharField(blank=True, max_length=30, verbose_name='Account Number')),
                ('account_holder', models.CharField(blank=True, max_length=100, verbose_name="Account Holder's Name")),
                ('momo_number', models.CharField(blank=True, max_length=10, null=True, verbose_name='Mobile Money Number')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
