# Generated by Django 2.2.6 on 2019-11-09 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0005_auto_20191107_1159'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stream',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playback_id', models.CharField(max_length=100, verbose_name='Stream Playback id')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='Stream Views')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Profile')),
            ],
        ),
    ]
