# Generated by Django 2.2.6 on 2019-11-07 12:57

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='activity',
            managers=[
                ('object', django.db.models.manager.Manager()),
            ],
        ),
    ]
