# Generated by Django 2.2.6 on 2019-11-07 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0002_auto_20191107_1257'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='activity',
            managers=[
            ],
        ),
    ]
