# Generated by Django 2.2.6 on 2019-11-03 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='qwqw-wq', editable=False, max_length=100),
            preserve_default=False,
        ),
    ]
