# Generated by Django 2.2.6 on 2019-11-05 06:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='image_3',
            field=models.ImageField(blank='True', null=True, upload_to='photo_image_filename'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_4',
            field=models.ImageField(blank='True', null=True, upload_to='photo_image_filename'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_5',
            field=models.ImageField(blank='True', null=True, upload_to='photo_image_filename'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image_6',
            field=models.ImageField(blank='True', null=True, upload_to='photo_image_filename'),
        ),
    ]
