# Generated by Django 2.2.6 on 2019-11-03 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='internalmemory',
            field=models.CharField(default='N/A', help_text='Internal Memory', max_length=10, verbose_name='Internal Memory'),
        ),
        migrations.AlterField(
            model_name='product',
            name='megapixels',
            field=models.CharField(default='N/A', help_text='Megapixels', max_length=10, verbose_name='Megapixels'),
        ),
        migrations.AlterField(
            model_name='product',
            name='pages',
            field=models.CharField(default='N/A', help_text='Number of Pages', max_length=10, verbose_name='Pages'),
        ),
        migrations.AlterField(
            model_name='product',
            name='ports',
            field=models.CharField(default='N/A', max_length=10, verbose_name='Number of Ports'),
        ),
    ]
